import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Logo from './components/Logo'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "New Sneakers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>
      
       <header 
         className="flex justify-center items-center gap-1 fixed z-10 w-full top-0 shadow-2xl text-white bg-gray-900 font-bold text-center p-3.5">
         <div className="flex justify-center items-center gap-1 border-white border-b-2">
          <h1 className="font-normal text-3xl font-lob">New Sneakers</h1> 
          <Logo />
         </div>
       </header>
       <section className="mt-[65px]">{children}</section>
      
      
    </body>
    
    </html>
  );
}
